### ISSUE TITLE
[Version 2.3.0] helm:lint cannot find values.yaml

### ISSUE THREAD

**Issue by d-huynh** [deviceinsight/helm-maven-plugin#28]
Hi,

I've just upgrade the plugin to the new 2.3.0 release from 2.1.0, and even tried 2.2.0, for our project, but I only encountered this problem on the 2.3.0 verion.

Here's my config:
```xml
<plugin>
    <groupId>com.deviceinsight.helm</groupId>
    <artifactId>helm-maven-plugin</artifactId>
    <version>2.3.0</version>
    <configuration>
        <chartName>${project.parent.artifactId}</chartName>
        <chartRepoUrl>${helm-repo.url}</chartRepoUrl>
        <helmVersion>${helm.version}</helmVersion>
        <valuesFile>src/test/helm/abc-app/values.yaml</valuesFile>
        <strictLint>false</strictLint>
        <skipSnapshots>false</skipSnapshots>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>package</goal>
                <goal>lint</goal>
                <goal>template</goal>
                <goal>deploy</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Linting passed in local, however, problem occurs when code got committed to Gitlab.

Gitlab config:
```yaml
mvn_test_job:
  stage: build
  script: >
    mvn clean verify --update-snapshots --batch-mode --activate-profiles sonar \
     -Dsonar.host.url=$SONAR_URL \
     -Dsonar.login=$SONAR_LOGIN \
     -Dsonar.analysis.mode=preview \
     -Dsonar.gitlab.project_id=$CI_PROJECT_ID \
     -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
     -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME \
     -Dsonar.gitlab.unique_issue_per_inline=true \
     -Dsonar.gitlab.url=https://gitlab.our-domain.com \
     -Dsonar.gitlab.user_token=$USER_TOKEN \
     -Dsonar.gitlab.disable_proxy=true \
     -Dsonar.gitlab.only_issue_from_commit_file=true \
     -Dstyle.color=always
  artifacts:
    paths:
      - "*/target/*-reports/*"
      - "*/target/*.log"
      - "*/target/generated-docs"
    when: always
    expire_in: 1 week
  except:
    - schedules
    - master
    - develop
    - tags
  tags:
    - dind
```

Error log:
```log
 [INFO] --- helm-maven-plugin:2.3.0:package (default) @ abc-app-standalone ---
 [INFO] Clear target directory to ensure clean target package
 [INFO] Created target helm directory
 [INFO] Successfully packaged chart and saved it to: /builds/abc/abc-app/abc-app-standalone/target/helm/abc-app-0.4.0-SNAPSHOT.tgz
 [INFO] 
 [INFO] --- helm-maven-plugin:2.3.0:lint (default) @ abc-app-standalone ---
 [INFO] Output: Error: open "/builds/abc/abc-app/abc-app-standalone/src/test/helm/abc-app/values.yaml": no such file or directory
 [INFO] ------------------------------------------------------------------------
```

Any idea why?
